/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArcPropertiesPanel.java
 *
 * Created on Jun 30, 2009, 8:32:10 PM
 */

package com.googlecode.sarasvati.editor.panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;

import com.googlecode.sarasvati.editor.GraphEditor;
import com.googlecode.sarasvati.editor.command.CommandStack;
import com.googlecode.sarasvati.editor.model.ArcState;
import com.googlecode.sarasvati.editor.model.EditorArc;

/**
 *
 * @author paul
 */
public class ArcPropertiesPanel extends javax.swing.JPanel {

  private static final long serialVersionUID = 1L;

    /** Creates new form ArcPropertiesPanel */
    public ArcPropertiesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arcNameLabel = new javax.swing.JLabel();
        arcNameInput = new javax.swing.JTextField();
        fromLabel = new javax.swing.JLabel();
        fromInput = new javax.swing.JComboBox();
        toLabel = new javax.swing.JLabel();
        toInput = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();

        arcNameLabel.setText(org.openide.util.NbBundle.getMessage(ArcPropertiesPanel.class, "ArcPropertiesPanel.arcNameLabel.text")); // NOI18N

        arcNameInput.setText(org.openide.util.NbBundle.getMessage(ArcPropertiesPanel.class, "ArcPropertiesPanel.arcNameInput.text")); // NOI18N

        fromLabel.setText(org.openide.util.NbBundle.getMessage(ArcPropertiesPanel.class, "ArcPropertiesPanel.fromLabel.text")); // NOI18N

        fromInput.setEditable(true);
        fromInput.setModel(getFromComboBoxModel());

        toLabel.setText(org.openide.util.NbBundle.getMessage(ArcPropertiesPanel.class, "ArcPropertiesPanel.toLabel.text")); // NOI18N

        toInput.setEditable(true);
        toInput.setModel(getToComboBoxModel());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        cancelButton.setText(org.openide.util.NbBundle.getMessage(ArcPropertiesPanel.class, "ArcPropertiesPanel.cancelButton.text")); // NOI18N
        cancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel1.add(cancelButton);

        applyButton.setText(org.openide.util.NbBundle.getMessage(ArcPropertiesPanel.class, "ArcPropertiesPanel.applyButton.text")); // NOI18N
        applyButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel1.add(applyButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fromLabel)
                    .addComponent(arcNameLabel)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arcNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arcNameLabel)
                    .addComponent(arcNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(fromInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JTextField arcNameInput;
    private javax.swing.JLabel arcNameLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox fromInput;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox toInput;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables

    private ComboBoxModel getToComboBoxModel ()
    {
      return new DefaultComboBoxModel();
    }

    private ComboBoxModel getFromComboBoxModel ()
    {
      return new DefaultComboBoxModel();
    }

    public void setup (final JDialog dialog,
                       final EditorArc arc)
    {
      cancelButton.addActionListener( new ActionListener()
      {
        @Override
        public void actionPerformed (ActionEvent e)
        {
          dialog.setVisible( false );
        }
      });

      applyButton.addActionListener( new ActionListener()
      {
        @Override
        public void actionPerformed (final ActionEvent e)
        {
          ArcState newState = new ArcState( arcNameInput.getText(), null, null );
          CommandStack.editArc( GraphEditor.getInstance().getCurrentScene(), arc, newState );
          dialog.setVisible( false );
        }
      });

      ArcState state = arc.getState();
      arcNameInput.setText( state.getLabel() );

      if ( !arc.isExternalInArc() )
      {
        if ( arc.isExternalOutArc() )
        {
          fromLabel.setText( "To" );
          toLabel.setVisible( false );
          toInput.setVisible( false );
        }
        else
        {
          fromLabel.setVisible( false );
          fromInput.setVisible( false );
        }
      }

      if ( !arc.isExternalOutArc() )
      {
        toLabel.setVisible( false );
        toInput.setVisible( false );
      }
    }
}
