/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralPreferencesPanel.java
 *
 * Created on Jul 4, 2009, 1:31:56 PM
 */

package com.googlecode.sarasvati.editor.panel;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author paul
 */
public class GeneralPreferencesPanel extends BasePrefsPage {

    private static final long serialVersionUID = 1L;

    /** Creates new form GeneralPreferencesPanel */
    public GeneralPreferencesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultNodeTypeLabel = new javax.swing.JLabel();
        defaultNodeTypeInput = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkLibraryRecursiveInput = new javax.swing.JCheckBox();
        libraryInput = new javax.swing.JTextField();
        libraryBrowseButton = new javax.swing.JButton();

        defaultNodeTypeLabel.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.defaultNodeTypeLabel.text")); // NOI18N

        defaultNodeTypeInput.setModel(getNodeTypesModel());

        jButton2.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.jButton2.text")); // NOI18N

        jButton3.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.jButton3.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.jLabel1.text")); // NOI18N

        checkLibraryRecursiveInput.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.checkLibraryRecursiveInput.text")); // NOI18N

        libraryInput.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.libraryInput.text")); // NOI18N

        libraryBrowseButton.setText(org.openide.util.NbBundle.getMessage(GeneralPreferencesPanel.class, "GeneralPreferencesPanel.libraryBrowseButton.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkLibraryRecursiveInput)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(libraryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libraryBrowseButton))
                    .addComponent(jLabel1))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libraryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libraryBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkLibraryRecursiveInput)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(defaultNodeTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultNodeTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultNodeTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultNodeTypeLabel))
                .addGap(296, 296, 296)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkLibraryRecursiveInput;
    private javax.swing.JComboBox defaultNodeTypeInput;
    private javax.swing.JLabel defaultNodeTypeLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton libraryBrowseButton;
    private javax.swing.JTextField libraryInput;
    // End of variables declaration//GEN-END:variables

    public ComboBoxModel getNodeTypesModel ()
    {
      return new DefaultComboBoxModel( new String[] { "node", "script", "wait", "task" } );
    }

    @Override
    public void setup ()
    {
      // does nothing yet
    }
}
