/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenLibraryPanel.java
 *
 * Created on Aug 24, 2009, 3:18:16 PM
 */

package com.googlecode.sarasvati.editor.panel;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
import javax.swing.ListModel;

/**
 *
 * @author paul
 */
public class ContentAssistPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /** Creates new form OpenLibraryPanel */
    public ContentAssistPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pdList = new javax.swing.JList();

        setMaximumSize(new java.awt.Dimension(330, 425));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(259, 131));

        pdList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pdList.setModel(getListModel());
        pdList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(pdList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList pdList;
    // End of variables declaration//GEN-END:variables

    private final DefaultListModel listModel = new DefaultListModel();

    public ListModel getListModel ()
    {
      return listModel;
    }

    public void setup (final JDialog dialog)
    {
      final Action enterAction = new AbstractAction()
      {
        private static final long serialVersionUID = 1L;

        @Override
        public void actionPerformed (final ActionEvent e)
        {
          // openSelected();
        }
      };

      final Action escapeAction = new AbstractAction()
      {
        private static final long serialVersionUID = 1L;

        @Override
        public void actionPerformed (final ActionEvent e)
        {
          dialog.setVisible( false );
          dialog.dispose();
        }
      };

      KeyStroke enterStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0);
      KeyStroke escapeStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,0);
      //nameInput.getInputMap().put( enterStroke, enterAction );
      //nameInput.getInputMap().put( escapeStroke, escapeAction );
      pdList.getInputMap().put( enterStroke, "pdlist:ENTER" );
      pdList.getActionMap().put( "pdlist:ENTER", enterAction );
      pdList.getInputMap().put( escapeStroke, "pdlist:ESCAPE" );
      pdList.getActionMap().put( "pdlist:ESCAPE", escapeAction );

      pdList.addMouseListener( new MouseAdapter()
      {
        @Override
        public void mouseClicked (final MouseEvent e)
        {
          if ( e.getClickCount() == 2 && e.getButton() == MouseEvent.BUTTON1 )
          {
            // openSelected();
          }
        }
      });

      listModel.removeAllElements();

      listModel.addElement( "ItemAction.isAdd" );
      listModel.addElement( "ItemAction.isMod" );
      listModel.addElement( "ItemAction.isDisc" );
    }
}
