//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.09.12 at 10:39:12 AM EDT
//

package com.googlecode.sarasvati.editor.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.googlecode.sarasvati.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: com.googlecode.sarasvati.xml
   *
   */
  public ObjectFactory ()
  {
    // default constructor
  }

  /**
   * Create an instance of {@link XmlEditorExternal }
   */
  public XmlEditorExternal createExternal ()
  {
    return new XmlEditorExternal();
  }

  /**
   * Create an instance of {@link XmlEditorNode }
   */
  public XmlEditorNode createNode ()
  {
    return new XmlEditorNode();
  }

  /**
   * Create an instance of {@link XmlEditorProperties }
   *
   */
  public XmlEditorProperties createEditorProperties ()
  {
    return new XmlEditorProperties();
  }
}
